version: 2
jobs:
  build:
    docker:
      # CircleCI images available at https://hub.docker.com/r/circleci/
      - image: cimg/node:22.14.0
    working_directory: ~/github.com/orgs/prediza/teams/prediza-finance
    #resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Node Version
          command: |
            node --version
      - run:
          name: NPM version
          command: |
            npm --version
      - run:
          name: NPM Install
          command: |
            npm install
      - run:
          name: NPM Build
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      enabled: true
    working_directory: ~/github.com/orgs/prediza/teams/prediza-finance
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to AWS S3
          command: |
            sudo apt-get update
            sudo apt-get install awscli
            aws s3 sync dist s3://prediza-finance/finance/ --delete --exclude '*.png' --exclude '*.css' --exclude '*.js' --exclude '*.xml' --exclude '*.woff2' --content-type="text/html"
            aws s3 sync dist s3://prediza-finance/finance/ --delete --exclude '*' --include '*.png' --include '*.css' --include '*.js' --include '*.xml' --include '*.woff2' --cache-control max-age=31536000,public
      - run:
          name: Cloudfront invalidation
          command: |
            aws cloudfront create-invalidation --distribution-id EEUXKYKQDIS7S --paths /finance/*
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
